<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Male' => 'Monsieur',
    'Female' => 'Madame',

    // Invitation mail subejct
    'Invitation to Vote at LES GLOBES DE CRISTAL' => 'Cérémonie des Globes de Cristal 2017/Ouverture des votes',
    // Invitation mail body
    '{gender} {name},
<p></p>
<p>Kindly participate to 2016 edtion of LES GLOBES DE CRISTAL voting event.</p>
<p>Please remember the voting event will be closed in one month.</p>
<p>You can login to vote by clicking below link:</p>
<p>Link: {url}</p>
<p>Sincerely,</p>' => '<p>{gender} {name},</p>
<p>Nous avons le plaisir de vous annoncer l’ouverture des votes qui désigneront les quatorze lauréats de la 11ème cérémonie des Globes de Cristal.</p>
<p>Le Jury, présidé par Mademoiselle Catherine Deneuve, a établi une liste de 5 nommés dans les domaines de l’Art et de la Culture.<br>En 2017, cette nouvelle édition s\'ouvrira à l\'international avec l\'arrivée de deux nouvelles catégories, «Meilleur film étranger» et «Meilleure série télévisée étrangère».</p>
<p>Nous sommes heureux de vous inviter à découvrir la liste des nommés 2017 et de vous laisser définir, pour chaque catégorie, vos lauréats. <br>Pour voter, il vous suffit de cliquer sur le lien que vous trouverez ci-dessous : </p>
<p><a href="{url}" target="_blank">Accéder aux votes</a></p>
<p>{url}</p>
<p>La clôture des votes aura lieu le jeudi 4 Janvier 2017 à Minuit.</p>
<p>Nous vous remercions pour votre implication, sans laquelle les Globes de Cristal n’auraient pu devenir un rendez-vous incontournable.<br>Nous vous donnons rendez-vous le lundi 30 Janvier 2017 pour découvrir les lauréats.</p>
<br>
<p>Pour toute information complémentaire, vous pouvez nous contacter par mail à presse@globesdecristal.com.</p>
<p>Cordialement.</p>
<br>
',
    'Dear {name},<p>Please check the following voting results.</p>' => '<p>Cher Maitre Albou,</p><p>Veuillez trouver ci joint, la liste des lauréats en cours, exportée via le tableau de bord du module de vote.</p><br>',

    '<p>Monsieur/Madame {name},</p>
<br>
<p>Nous avons le plaisir de vous annoncer l’ouverture des votes qui désigneront les quatorze lauréats de la 11ème cérémonie des Globes de Cristal.</p>',

    // Summary mail subject
    'Your voting summary at ' => 'Confirmation de vote/',

    // Summary mail body
    '{gender} {name},
<p></p>
<p>Thank you for completing the voting process.</p>
<p>Please check the following vote summary:</p>' => '<p>{gender} {name},</p>
<p>Vos votes ont bien été pris en compte, nous vous remercions pour votre participation.</p>
<p>Cette 11ème édition des Globes de cristal sera, une fois de plus grâce à votre implication, représentative des talents qui ont fait briller l’année 2016 dans les domaines de l’Art et de le Culture.</p>
<p>Nous vous donnons rendez-vous lundi 30 Janvier 2017, en direct du Lido de Paris, pour découvrir les lauréats.</p>
<br>
<p>Pour toute information complémentaire, vous pouvez nous contacter par mail à presse@globesdecristal.com.</p>
<br>
<p>Retrouvez ci-dessous, le récapitulatif de vos votes : </p>',

    // Summary mail footer
    '<p>Sincerely,</p>' => '<br><p>Cordialement.</p><br>',

    'Email: ' => '',
    'Impact {name},
<p></p>
<p>Your password was successfully changed.
<br>Thank you.</p>' => '',
    'Impact,
<p></p>
<p>Please, click on the following link to reset your password {link}
<br>Thank you.</p>' => '',


    // First/Second/Third/Forth/Final reminder subject
    'LES GLOBES DE CRISTAL ceremony in 2017/Vote' => 'Cérémonie des Globes de Cristal 2017/Vote',

    // First/Second/Third/Forth reminder body
    '{gender} {name},
<p></p>
<p>You have not participated in the vote to select the winners of the 11th ceremony of LES GLOBES DE CRISTAL.</p>
<p>The French press awards rewards LES GLOBES DE CRISTAL in the disciplines of Arts and Culture for the year 2016.</p>
<p>The Jury, chaired by Ms Catherine Deneuve, has established a list of five nominated in fourteen categories representative of each cultural area:</p>
<p>$nbsp;- Best Film</p>
<p>$nbsp;- Best Actress</p>
<p>$nbsp;- Best Actor</p>
<p>$nbsp;- Best Theatre Piece</p>
<p>You can login to vote by clicking below link:</p>
<p>Link: {url}</p>
<p>Sincerely,</p>' => '<p>{gender} {name},</p>
<p>Vous n’avez pas encore pris part au vote pour élire les lauréats de la 11ème cérémonie des Globes de Cristal.</p>
<p>La presse française décerne les récompenses des Globes de Cristal dans les disciplines de l’Art et de la Culture pour l’année 2016.<br>Le Jury, présidé par Mademoiselle Catherine Deneuve, a établi une liste de 5 nommés dans quatorze catégories représentatives de chaque domaine artistique et culturel : </p>
<br>
<p>
-	Meilleur Film<br>
-	Meilleur Film étranger<br>
-	Meilleure Actrice<br>
-	Meilleur Acteur<br>
-	Meilleure Pièce de théâtre<br>
-	Meilleure Comédienne<br>
-	Meilleur Comédien<br>
-	Meilleur One man show<br>
-	Meilleure Comédie musicale<br>
-	Meilleur Roman-Essai<br>
-	Meilleure Interprète féminine<br>
-	Meilleur Interprète masculin<br>
-	Meilleur Série télévisée/Téléfilm<br>
-	Meilleure Série télévisée étrangère
</p>
<br>
<p>Nous avons l’honneur et le plaisir de vous convier à élire les artistes qui ont marqué l’année 2016. </p>
<p>Pour voter, il vous suffit de cliquer sur le lien que vous trouverez ci-dessous : </p>
<p><a href="{url}" target="_blank">Accéder aux votes</a></p>
<p>{url}</p>
<p>Les lauréats seront dévoilés le lundi 30 Janvier 2017 lors de la 11ème cérémonie en direct du Lido.</p>
<p>Nous vous remercions d’avance pour votre participation.<br>La clôture des votes aura lieu le jeudi 4 Janvier 2017 à Minuit.</p>
<br>
<p>Pour toute information complémentaire, vous pouvez nous contacter par mail à presse@globesdecristal.com.</p>
<p>Bien cordialement.</p><br>',

    // Final reminder body
    '{gender} {name},
<p></p>
<p>The 11th ceremony of the Crystal Globe voting closes tonight.</p>
<p>The Jury, chaired by Ms Catherine Deneuve, has established a list of five nominated in fourteen categories representative of each cultural area:</p>
<p>$nbsp;- Best Film</p>
<p>$nbsp;- Best Actress</p>
<p>$nbsp;- Best Actor</p>
<p>$nbsp;- Best Theatre Piece</p>
<p>You can login to vote by clicking below link:</p>
<p>Link: {url}</p>
<p>Sincerely,</p>' => '<p>{gender} {name},</p>
<p>La 11ème cérémonie des Globes de Cristal clôturera ses votes ce soir à Minuit.<br>Le Jury, présidé par Mademoiselle Catherine Deneuve, a établi une liste de 5 nommés dans quatorze catégories représentatives de chaque domaine artistique et culturel :</p><br>
<p>-	Meilleur Film<br>
-	Meilleur Film étranger<br>
-	Meilleure Actrice<br>
-	Meilleur Acteur<br>
-	Meilleure Pièce de théâtre<br>
-	Meilleure Comédienne<br>
-	Meilleur Comédien<br>
-	Meilleur One man show<br>
-	Meilleure Comédie musicale<br>
-	Meilleur Roman-Essai<br>
-	Meilleure Interprète féminine<br>
-	Meilleur Interprète masculin<br>
-	Meilleur Série télévisée/Téléfilm<br>
-	Meilleure Série télévisée étrangère</p>
<br>
<p>Il ne vous reste que très peu de temps pour élire les artistes de l’année 2016 et désigner vos lauréats pour chacune des quatorze catégories.</p>
<p>Pour voter, il vous suffit de cliquer sur le lien que vous trouverez ci-dessous : </p>
<p><a href="{url}" target="_blank">Accéder aux votes</a></p>
<p>{url}</p>
<p>La clôture des votes aura lieu le jeudi 4 Janvier 2017 à Minuit.<br>Nous comptons une nouvelle fois sur votre participation, qui reste très importante pour faire vivre cet événement.</p><br>
<p>Pour toute information complémentaire, vous pouvez nous contacter par mail à presse@globesdecristal.com.</p>
<p>Cordialement.</p><br>',

    'LES GLOBES DE CRISTAL' => '',
    'LES GLOBES DE CRISTAL © {year}. All Rights Reserved.' => '',
    'Tel: ' => '',
    'Voting results at ' => 'Liste lauréats en cours',

    '<br>Deposit charged:{amount}({currency})' => '@@Dépôt de garantie {amount}({currency})@@',
    '<br>Initial rent charged:{cost}({currency})' => '@@Montant du loyer {cost}({currency})@@',
    '<br>Initial rental charged:{cost}({currency})' => '@@@@',
    'All rental payment attempts have failed for "{code}"' => '@@Echec des tentatives de paiement du loyer pour le logement "{code}"@@',
    'Card expiration on {date}' => '@@Expiration de votre carte bancaire le {date}@@',
    'Copyright © {year} Impact. All Rights Reserved.' => '@@@@',
    'Copyright © {year} Olarent. All Rights Reserved.' => '@@Droits d\'auteurs et de reproduction; {year} Olarent. Tous droits réservés.@@',
    'Dear Aruna,
<p>This is to inform that next payment to the property "12365" scheduled on 2016-03-25.</p>
<p>hello 123456 .</p>
Thank you.' => '@@@@',
    'Dear {name},
<p></p>
<p>This message to inform that you have successfully created your Impact account.
<br>Thank you.</p>' => '@@@@',
    'Email:' => '@@Email:@@',
    'Failed rental payment for "{code}"' => '@@Echec du paiement du loyer pour le logement "{code}"@@',
    'Impact poll management system.' => '@@@@',
    'Impact {name},
<p></p>
<p>This message to inform that your configured credit card is about to expire on {date}, please configure a new card.
<br>Thank you.</p>' => '@@@@',
    'Impact {name},
<p></p>
<p>This message to inform you that the next payment to the rental "{code}" is scheduled on {nextChargingDate}.
<br>Thank you.</p>' => '@@@@',
    'Impact {name},
<p></p>
<p>This message to inform you that the rental "{code}" has been terminated by {terminatorName}.
<br>Thank you.</p>' => '@@@@',
    'Impact {name},
<p></p>
<p>This message to inform you that you have received all the pending payments of {amount}({currency}) for the rental "{code}"
<br>Thank you.</p>' => '@@@@',
    'Impact {name},
<p></p>
<p>This message to inform you that you have successfully made the pending payment of {amount}({currency}) for the property "{code}"
<br>Thank you.</p>' => '@@@@',
    'Impact {name},
<p></p>
<p>This message to inform you that you have terminated the rental "{code}".
<br>Thank you.</p>' => '@@@@',
    'Impact {ownerName},
<p></p>
<p>You have received a rental request from {tenantName}
<br>rental code is {propertyCode}
<br>Please respond as soon as you can to this inquiry.
<br>Thank you.</p>' => '@@@@',
    'Impact {ownerName},
<p>You have accepted the rental request of {tenantName} for the rental {propertyCode}.
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => '@@@@',
    'Impact {tenantName},
<p></p>
<p>Congratulations ! Your rental request was accepted by {ownerName}
<br>The rental code is {propertyCode}
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => '@@@@',
    'Impact {tenantName},
<p></p>
<p>Sorry your request for {propertyCode} was not accepted by {ownerName}, however he wishes you the best of luck in your search.
<br>We hope you will find another place you like on Olarent.
<br>Thank you.</p>' => '@@@@',
    'Impact {toName}
<p></p>
<p>This message to inform you that the {amount} ({currency}) payment to the property "{code}" has failed. Please check your payment plan. We will try to complete the payment on {date} again.
<br>Thank you.</p>' => '@@@@',
    'Impact {toName}
<p></p>
<p>This message to inform you, your monthly rent have been charged {amount} ({currency}) for the property "{code}"
<br>Thank you.</p>' => '@@@@',
    'Impact {toName},
<p></p>
<p>This message to inform you that all charging attempts made to the property "{code}" have failed. Please get in touch
with your landlord and check with your bank or update your Credit/Debit card information.
<br>Thank you.</p>' => '@@@@',
    'Impact {toName},
<p></p>
<p>This message to inform you that all rental payment attempts have failed for "{code}".
Please get in touch with your tenant, we have advised him to update his payment method on Olarent.
<br>Thank you.</p>' => '@@@@',
    'Impact {toName},
<p></p>
<p>This message to inform you that the {amount} ({currency}) payment for the property "{code}" has failed.
We will try again to complete the payment on {date}.
<br>Thank you.</p>' => '@@@@',
    'Impact {toName},
<p></p>
<p>This message to inform you, you have received the payment of {amount} ({currency}) for the property "{code}"
<br>Thank you.</p>' => '@@@@',
    'Impact {toName},
<p></p>
<p>You have received a review feedback from your former landlord {fromName}
<br>Thank you.</p>' => '@@@@',
    'Impact {toName},
<p></p>
<p>You have received a review request from your former Tenant {fromName}
<br>Thank you for your contribution !</p>' => '@@@@',
    'Impact,
<p></p>
<p>{ownerName} has invited you to join Olarent to get to know you better and to make paying your rent easy and problem free.
<br>With Olarent you can pay your rent via Credit/Debit card and automate monthly payments.</p>
<p>Message from {ownerName}
<br>{message}
<br>Go to our web app here:{appDownloadLink}
<br>Thank you.</p>' => '@@@@',
    'Ola {name},
<p></p>
<p>This message to inform that you have successfully created your Olarent account.
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Nous vous informons que votre compte OlaRent a été créé avec succès.
<br>Merci.</p>@@',
    'Ola {name},
<p></p>
<p>This message to inform that your configured credit card is about to expire on {date}, please configure a new card.
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Nous vous informons que votre carte de crédit configurée arrive à expiration le {date}, veuillez s\'il vous plait configurer une autre carte.
<br>Merci.</p>@@',
    'Ola {name},
<p></p>
<p>This message to inform you that the next payment to the rental "{code}" is scheduled on {nextChargingDate}.
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Nous vous informons que le prochain paiement de votre loyer de pour le logement "{code}" est programmé pour le {nextChargingDate}.
<br>Merci.</p>@@',
    'Ola {name},
<p></p>
<p>This message to inform you that the rental "{code}" has been terminated by {terminatorName}.
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Nous vous informons que {terminatorName} a mis fin à la location du logement "{code}".
<br>Merci.</p>@@',
    'Ola {name},
<p></p>
<p>This message to inform you that you have received all the pending payments of {amount}({currency}) for the rental "{code}"
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Nous vous informons que vous avez reçu le paiement en attente de {amount}({currency}) pour le logement "{code}".
<br>Merci.</p>@@',
    'Ola {name},
<p></p>
<p>This message to inform you that you have successfully made the pending payment of {amount}({currency}) for the property "{code}"
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Nous vous informons que vous avez effectué avec succès le paiement en attente de {amount}({currency}) pour le loyer du logement "{code}".
<br>Merci.</p>@@',
    'Ola {name},
<p></p>
<p>This message to inform you that you have terminated the rental "{code}".
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Nous vous informons que vous avez supprimé le logement "{code}".
<br>Merci.</p>@@',
    'Ola {name},
<p></p>
<p>Your password was successfully changed.
<br>Thank you.</p>' => '@@Ola {name},
<p></p>
<p>Votre mot de passe a été réinitialisé avec succès.
<br>Merci.</p>@@',
    'Ola {ownerName},
<p></p>
<p>You have received a rental request from {tenantName}
<br>rental code is {propertyCode}
<br>Please respond as soon as you can to this inquiry.
<br>Thank you.</p>' => '@@Ola {ownerName},
<p></p>
<p>Vous avez reçu une demande de location de {tenantName}
<br>Code logement {propertyCode}
<br>Nous vous invitons à y répondre.
<br>Merci.</p>@@',
    'Ola {ownerName},
<p>You have accepted the rental request of {tenantName} for the rental {propertyCode}.
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => '@@Ola {ownerName},
<p>Nous vous informons que vous avez accepté une demande de location de {tenantName} pour le logement {propertyCode}.
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>@@',
    'Ola {tenantName},
<p></p>
<p>Congratulations ! Your rental request was accepted by {ownerName}
<br>The rental code is {propertyCode}
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => '@@Ola {tenantName},
<p></p>
<p>Féliciations! Votre demande de location a été acceptée par {ownerName}
<br>Code logement {propertyCode}
{msgKeymoney}
{msgInitRent}
<br>Merci.</p>@@',
    'Ola {tenantName},
<p></p>
<p>Sorry your request for {propertyCode} was not accepted by {ownerName}, however he wishes you the best of luck in your search.
<br>We hope you will find another place you like on Olarent.
<br>Thank you.</p>' => '@@Ola {tenantName},
<p></p>
<p>Désolé, votre demande de location pour {propertyCode} n\'a pas été acceptée par {ownerName}. Il vous souhaite cependant une bonne recherche.
<br>En espérant qu\'une autre location vous convienne sur Olarent.
<br>Merci.</p>@@',
    'Ola {toName}
<p></p>
<p>This message to inform you that the {amount} ({currency}) payment to the property "{code}" has failed. Please check your payment plan. We will try to complete the payment on {date} again.
<br>Thank you.</p>' => '@@Ola {toName}
<p></p>
<p>Nous vous informons que le paiement du loyer de {amount} ({currency}) pour la  logement "{code}" a échoué. Veuillez vérifier votre moyen de paiement afin qu\'il puisse être complété avant le {date}..
<br>Merci.</p>@@',
    'Ola {toName}
<p></p>
<p>This message to inform you, your monthly rent have been charged {amount} ({currency}) for the property "{code}"
<br>Thank you.</p>' => '@@Ola {toName}
<p></p>
<p>Nous vous confirmons que le paiement de {amount} ({currency}) pour votre logement "{code}" a bien été effectué."
<br>Merci.</p>@@',
    'Ola {toName},
<p></p>
<p>This message to inform you that all charging attempts made to the property "{code}" have failed. Please get in touch
with your landlord and check with your bank or update your Credit/Debit card information.
<br>Thank you.</p>' => '@@Ola {toName},
<p></p>
<p>Nous vous informons que toutes les tentatives de paiements ont échoué pour la logement "{code}".
Veuillez prendre contact avec votre propriétaire et vous rapprocher de votre banque ou mettre à jour votre moyen de paiement dans Olarent.
<br>Merci.</p>@@',
    'Ola {toName},
<p></p>
<p>This message to inform you that all rental payment attempts have failed for "{code}".
Please get in touch with your tenant, we have advised him to update his payment method on Olarent.
<br>Thank you.</p>' => '@@Ola {toName},
<p></p>
<p>Nous vous informons que toutes les tentatives de paiement pour la location "{code}" ont échoué.
Veuillez prendre contact avec votre locataire, nous lui avons conseillé de mettre à jour son moyen de paiement sur Olarent.
<br>Merci.</p>@@',
    'Ola {toName},
<p></p>
<p>This message to inform you that the {amount} ({currency}) payment for the property "{code}" has failed.
We will try again to complete the payment on {date}.
<br>Thank you.</p>' => '@@Ola {toName},
<p></p>
<p>Nous vous informons que le paiement du loyer de {amount} ({currency}) pour la logement "{code}" a échoué.
Nous procèderons à une deuxieme tentative le {date}.
<br>Merci.</p>@@',
    'Ola {toName},
<p></p>
<p>This message to inform you, you have received the payment of {amount} ({currency}) for the property "{code}"
<br>Thank you.</p>' => '@@Ola {toName},
<p></p>
<p>Nous vous confirmons que vous avez reçu le paiement du loyer de {amount} ({currency}) pour votre logement "{code}".
<br>Merci.</p>@@',
    'Ola {toName},
<p></p>
<p>You have received a review feedback from your former landlord {fromName}
<br>Thank you.</p>' => '@@Ola {toName},
<p></p>
<p>Vous avez reçu une référence de votre ancien propriétaire {fromName}
<br>Merci.</p>@@',
    'Ola {toName},
<p></p>
<p>You have received a review request from your former Tenant {fromName}
<br>Thank you for your contribution !</p>' => '@@Ola {toName},
<p></p>
<p>Vous avez reçu une demande de référence venant de votre ancien locataire {fromName} Cela vous prendra quelques secondes !
<br>Merci de votre contribution et à bientôt! Nous serions heureux de faciliter les échanges et règlements de
loyers avec vos futurs locataires.</p>@@',
    'Ola,
<p></p>
<p>Please, click on the following link to reset your password {link}
<br>Thank you.</p>' => '@@Ola,
<p></p>
<p>Veuillez cliquer sur ce lien pour réinitialiser votre password {link}
<br>Merci.</p>@@',
    'Ola,
<p></p>
<p>{ownerName} has invited you to join Olarent to get to know you better and to make paying your rent easy and problem free.
<br>With Olarent you can pay your rent via Credit/Debit card and automate monthly payments.</p>
<p>Message from {ownerName}
<br>{message}
<br>Go to our web app here:{appDownloadLink}
<br>Thank you.</p>' => '@@Ola !,
<p></p>
<p>{ownerName}, propriétaire bailleur de votre appartement souhaite vous inviter à utiliser Olarent afin de faciliter
votre communication ainsi que les paiements de loyers. A vous de jouer!</p>
<p>Message de {ownerName}
<br>{message}
<br>Découvrez notre web app:{appDownloadLink}
<br>Merci.</p>@@',
    'Olarent Invitation from {ownerName}' => '@@Invitation Olarent de la part de {ownerName}@@',
    'Olarent property management system.' => '@@@@',
    'Pending payments have been made for "{code}"' => '@@Le paiement en attente a été effectué pour "{code}"@@',
    'Pending payments have been received for "{code}"' => '@@Le paiement en attente a été effectué pour "{code}"@@',
    'Rental  payment confirmation for "{code}"' => '@@Confirmation du paiement du loyer pour "{code}"@@',
    'Rental payment attempt has failed for "{code}"' => '@@La tentative de paiement du loyer a échoué pour "{code}"@@',
    'Rental payment confirmation' => '@@Confirmation de paiement du loyer@@',
    'Rental request accepted from {ownerName}' => '@@Demande de location acceptée par {ownerName}@@',
    'Rental request from {tenantName}' => '@@Demande de location de {tenantName}@@',
    'Rental termination confirmation for "{code}"' => '@@Confirmation de la fin de location pour "{code}"@@',
    'Rental termination for "{code}"' => '@@Fin de la location pour "{code}"@@',
    'Review feedback' => '@@Vous avez reçu une référence@@',
    'Review request from {fromName}' => '@@Demande de référence de {fromName}@@',
    'Tel:' => '@@@@',
    'The Olarent Team' => '@@L\'équipe Olarent@@',
    'The request was not accepted for the rental {propertyCode}' => '@@La demande de location n\'a pas été accepté pour le logement {propertyCode}@@',
    'This month rental payment on {nextChargingDate}' => '@@Le paiement de votre loyer est prévu pour le {nextChargingDate}@@',
    'Translate test' => '@@@@',
    'Unsubscribe' => '@@désinscription@@',
    'Welcome to Impact {name}' => '@@@@',
    'Welcome to Olarent {name}' => '@@Bienvenue sur Olarent {name}@@',
    'You have accepted a rental request for "{code}"' => '@@Vous avez accepté une demande de location pour "{code}"@@',
    'Reset password' => 'Modifiez votre mot de passe',

    // Custom token mail subject
    'Important: Modification of vote/Globes de Cristal' => 'Important : Modification vote/Globes de Cristal',
    // Custom token mail body
    '<p>{gender} {name},</p>
<p>Following the replacement, in the list of nominees, of the "Phantom of the Opera adaptation of the novel by Gaston Leroux, produced by Stage Entertainment in collaboration with The Really Useful Group, directed by Harold Prince (Theater Mogador) by" Timéo " Produced by Jérémie de Lacharrière, directed by Alex Goude (Casino de Paris), we invite you to vote exclusively for the category "Best Musical Comedy".</p>
<p>To vote, just click on the link below:</p>
<p><a href="{url}" target="_blank">Go to the vote</a></p>
<p>{url}</p>
<p>We apologize for the inconvenience and thank you for your participation.</p><br>
<p>Note: for more information, we invite you to visit the "Press" section, "Press Release" section of our website. <a href="http://www.globesdecristal.com" target="_blank">www.globesdecristal.com</a></p>
<p>Sincerely,</p><br>' => '<p>{gender} {name},</p>
<p>Suite au remplacement, dans la liste des nommés, du <b>«Fantôme de l\'Opéra»</b> adaptation du roman de Gaston Leroux, produit par Stage Entertainment en collaboration avec The Really Useful Group, mis en scène par Harold Prince (Théâtre Mogador) par <b>«Timéo»</b> produit par Jérémie de Lacharrière, mis en scène par Alex Goude (Casino de Paris), nous vous invitons à revoter <b>exclusivement</b> pour la catégorie <b>«Meilleure Comédie Musicale»</b>.</p>
<p>Pour voter, il vous suffit de cliquer sur le lien que vous trouverez ci-dessous : </p>
<p><a href="{url}" target="_blank">Accéder aux votes</a></p>
<p>{url}</p>
<p>Nous nous excusons de ce désagrément et vous remercions pour votre participation.</p><br>
<p>NB : pour plus d\'information, nous vous invitons à vous rendre dans l\'espace <b>«Presse»</b>, rubrique <b>«communiqué de presse»</b> de notre site internet. <a href="http://www.globesdecristal.com" target="_blank">www.globesdecristal.com</a></p>
<p>Cordialement.</p><br>',
];
